import type { Props, WidgetSpec } from '../types'
import { rootClass } from '../types'
import { pascal, styleAttr } from '../util'
import { indent, rootHtml } from '../render'
import { htmlToJsx, styleObject } from './jsx'

export interface ExportFile {
  name: string
  language: 'html' | 'css' | 'tsx' | 'ts' | 'vue' | 'svelte' | 'js' | 'json' | 'md'
  content: string
}

export interface ExportTarget {
  id: string
  label: string
  hint: string
  files: ExportFile[]
}

/** Compose a file from lines. `false` and `null` entries drop out. */
function lines(...rows: (string | false | null | undefined)[]): string {
  return rows.filter((r): r is string => typeof r === 'string').join('\n') + '\n'
}

function headerLines(spec: WidgetSpec, style: 'block' | 'html'): string {
  const open = style === 'html' ? '<!--' : '/*'
  const close = style === 'html' ? '-->' : '*/'
  return [
    open,
    `  ${spec.name} - ${spec.blurb}`,
    '  Generated by Widgetry. No runtime, no dependency, yours to edit.',
    close,
  ].join('\n')
}

function tokenEntries(spec: WidgetSpec, props: Props): [string, string][] {
  return Object.entries(spec.vars(props))
}

function tokenCssBlock(spec: WidgetSpec, props: Props, pad = '  '): string {
  return tokenEntries(spec, props)
    .map(([k, v]) => `${pad}${k}: ${v};`)
    .join('\n')
}

function scriptBody(spec: WidgetSpec, props: Props): string | null {
  return spec.script?.(props) ?? null
}

function initFn(body: string, typed: boolean, pad = ''): string {
  const sig = typed ? 'function init(root: any) {' : 'function init(root) {'
  return [pad + sig, indent(body, pad + '  '), pad + '}'].join('\n')
}

/* ---------------------------------------------------------------- html ---- */

function htmlTarget(spec: WidgetSpec, props: Props): ExportTarget {
  const cls = rootClass(spec)
  const body = scriptBody(spec, props)
  const content = lines(
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    `<title>${spec.name}</title>`,
    headerLines(spec, 'html'),
    '<style>',
    'body {',
    '  margin: 0;',
    '  min-height: 100vh;',
    '  display: grid;',
    '  place-items: center;',
    '  background: #d6d8da;',
    '}',
    '',
    spec.css(props),
    '</style>',
    '</head>',
    '<body>',
    rootHtml(spec, props),
    body && '<script>',
    body && initFn(body, false),
    body && `init(document.querySelector('.${cls}'));`,
    body && '</script>',
    '</body>',
    '</html>',
  )
  return {
    id: 'html',
    label: 'HTML',
    hint: 'One self contained file. Open it in a browser and it runs.',
    files: [{ name: `${spec.id}.html`, language: 'html', content }],
  }
}

/* --------------------------------------------------------------- react ---- */

function reactTarget(spec: WidgetSpec, props: Props): ExportTarget {
  const Name = pascal(spec.id)
  const cls = rootClass(spec)
  const body = scriptBody(spec, props)
  const jsx = htmlToJsx(spec.markup(props), '      ', 'CSSProperties')
  const tokens = styleObject(
    tokenEntries(spec, props)
      .map(([k, v]) => `${k}: ${v}`)
      .join('; '),
  )

  const tsx = lines(
    headerLines(spec, 'block'),
    body && "import { useEffect, useRef } from 'react'",
    "import type { CSSProperties } from 'react'",
    `import './${Name}.css'`,
    '',
    `export interface ${Name}Props {`,
    '  className?: string',
    '  /** Override any design token listed in `tokens` below. */',
    '  style?: CSSProperties',
    '}',
    '',
    '/** Every colour and size this widget reads. Override them through `style`. */',
    `export const tokens: CSSProperties = ${tokens}`,
    '',
    body && initFn(body, true),
    body && '',
    `export default function ${Name}({ className, style }: ${Name}Props) {`,
    body && '  const ref = useRef<HTMLDivElement>(null)',
    body && '',
    body && '  useEffect(() => {',
    body && '    if (!ref.current) return',
    body && '    return init(ref.current)',
    body && '  }, [])',
    '',
    '  return (',
    '    <div',
    body && '      ref={ref}',
    `      className={['${cls}', className].filter(Boolean).join(' ')}`,
    '      style={{ ...tokens, ...style }}',
    '    >',
    jsx,
    '    </div>',
    '  )',
    '}',
  )

  const css = lines(headerLines(spec, 'block'), '', spec.css(props))

  return {
    id: 'react',
    label: 'React',
    hint: 'A typed component plus its stylesheet. Drop both into your app.',
    files: [
      { name: `${Name}.tsx`, language: 'tsx', content: tsx },
      { name: `${Name}.css`, language: 'css', content: css },
    ],
  }
}

/* ----------------------------------------------------------------- vue ---- */

function vueTarget(spec: WidgetSpec, props: Props): ExportTarget {
  const Name = pascal(spec.id)
  const cls = rootClass(spec)
  const body = scriptBody(spec, props)
  const content = lines(
    headerLines(spec, 'html'),
    body && '<script setup lang="ts">',
    body && "import { onBeforeUnmount, onMounted, ref } from 'vue'",
    body && '',
    body && 'const root = ref<HTMLElement | null>(null)',
    body && 'let dispose: (() => void) | void',
    body && '',
    body && initFn(body, true),
    body && '',
    body && 'onMounted(() => {',
    body && '  if (root.value) dispose = init(root.value)',
    body && '})',
    body && '',
    body && 'onBeforeUnmount(() => {',
    body && '  if (dispose) dispose()',
    body && '})',
    body && '</script>',
    body && '',
    '<template>',
    `  <div${body ? ' ref="root"' : ''} class="${cls}" :style="{`,
    tokenEntries(spec, props)
      .map(([k, v]) => `    '${k}': '${v}',`)
      .join('\n'),
    '  }">',
    indent(spec.markup(props), '    '),
    '  </div>',
    '</template>',
    '',
    '<style>',
    spec.css(props),
    '</style>',
  )
  return {
    id: 'vue',
    label: 'Vue',
    hint: 'A single file component carrying the same markup and stylesheet.',
    files: [{ name: `${Name}.vue`, language: 'vue', content }],
  }
}

/* -------------------------------------------------------------- svelte ---- */

function svelteTarget(spec: WidgetSpec, props: Props): ExportTarget {
  const Name = pascal(spec.id)
  const cls = rootClass(spec)
  const body = scriptBody(spec, props)
  const inline = tokenEntries(spec, props)
    .map(([k, v]) => `${k}: ${v}`)
    .join('; ')
  const content = lines(
    headerLines(spec, 'html'),
    body && '<script lang="ts">',
    body && "  import { onMount } from 'svelte'",
    body && '',
    body && '  let root: HTMLElement',
    body && '',
    body && initFn(body, true, '  '),
    body && '',
    body && '  onMount(() => {',
    body && '    return init(root)',
    body && '  })',
    body && '</script>',
    body && '',
    `<div${body ? ' bind:this={root}' : ''} class="${cls}" style="${inline}">`,
    indent(spec.markup(props), '  '),
    '</div>',
    '',
    '<style>',
    spec.css(props),
    '</style>',
  )
  return {
    id: 'svelte',
    label: 'Svelte',
    hint: 'A Svelte component. The style block stays global so the tokens remain overridable.',
    files: [{ name: `${Name}.svelte`, language: 'svelte', content }],
  }
}

/* ------------------------------------------------------- web component ---- */

function webComponentTarget(spec: WidgetSpec, props: Props): ExportTarget {
  const cls = rootClass(spec)
  const tag = `wg-${spec.id}`
  const Class = `${pascal(spec.id)}Element`
  const body = scriptBody(spec, props)
  const content = lines(
    headerLines(spec, 'block'),
    'const CSS = String.raw`',
    spec.css(props).replace(/`/g, '\\`'),
    '`',
    '',
    'const MARKUP = String.raw`',
    rootHtml(spec, props).replace(/`/g, '\\`'),
    '`',
    '',
    body && initFn(body, false),
    body && '',
    `export class ${Class} extends HTMLElement {`,
    '  #dispose',
    '',
    '  connectedCallback() {',
    '    if (this.shadowRoot) return',
    "    const shadow = this.attachShadow({ mode: 'open' })",
    "    const style = document.createElement('style')",
    '    style.textContent = CSS',
    // `insertAdjacentHTML` lives on Element; a ShadowRoot is a DocumentFragment
    // and does not have it. A template parses the markup once and hands over a
    // fragment, which keeps the stylesheet first in the shadow tree.
    "    const template = document.createElement('template')",
    '    template.innerHTML = MARKUP',
    '    shadow.append(style, template.content)',
    body && `    this.#dispose = init(shadow.querySelector('.${cls}'))`,
    '  }',
    '',
    '  disconnectedCallback() {',
    '    if (this.#dispose) this.#dispose()',
    '    this.#dispose = undefined',
    '  }',
    '}',
    '',
    `if (!customElements.get('${tag}')) customElements.define('${tag}', ${Class})`,
  )
  return {
    id: 'webcomponent',
    label: 'Web Component',
    hint: `Import once, then write <${tag}></${tag}> in any framework, or none.`,
    files: [{ name: `${spec.id}.element.js`, language: 'js', content }],
  }
}

/* ------------------------------------------------------------ css only ---- */

function cssTarget(spec: WidgetSpec, props: Props): ExportTarget {
  const cls = rootClass(spec)
  const snippet = lines(
    headerLines(spec, 'html'),
    `<div class="${cls}"${styleAttr(spec.vars(props))}>`,
    indent(spec.markup(props)),
    '</div>',
  )
  const sheet = lines(
    headerLines(spec, 'block'),
    '',
    `.${cls} {`,
    tokenCssBlock(spec, props),
    '}',
    '',
    spec.css(props),
  )
  return {
    id: 'css',
    label: 'HTML + CSS',
    hint: 'Markup and stylesheet kept apart, for templating engines and design tools.',
    files: [
      { name: `${spec.id}.html`, language: 'html', content: snippet },
      { name: `${spec.id}.css`, language: 'css', content: sheet },
    ],
  }
}

/* -------------------------------------------------------------- config ---- */

function configTarget(spec: WidgetSpec, props: Props): ExportTarget {
  const config = {
    generator: 'widgetry',
    version: 1,
    widget: spec.id,
    name: spec.name,
    props,
    tokens: spec.vars(props),
  }
  return {
    id: 'config',
    label: 'Config',
    hint: 'The exact knob positions. Paste it back into the studio to restore this build.',
    files: [{ name: `${spec.id}.widgetry.json`, language: 'json', content: JSON.stringify(config, null, 2) + '\n' }],
  }
}

export function buildTargets(spec: WidgetSpec, props: Props): ExportTarget[] {
  return [
    htmlTarget(spec, props),
    reactTarget(spec, props),
    vueTarget(spec, props),
    svelteTarget(spec, props),
    webComponentTarget(spec, props),
    cssTarget(spec, props),
    configTarget(spec, props),
  ]
}

export function readmeFor(spec: WidgetSpec, props: Props): ExportFile {
  const fileList = buildTargets(spec, props)
    .map((t) => `- \`${t.files.map((f) => f.name).join('`, `')}\` : ${t.hint}`)
    .join('\n')

  return {
    name: 'README.md',
    language: 'md',
    content: lines(
      `# ${spec.name}`,
      '',
      spec.blurb,
      '',
      'Exported from Widgetry with these settings:',
      '',
      '```json',
      JSON.stringify(props, null, 2),
      '```',
      '',
      '## What is in this folder',
      '',
      fileList,
      '',
      '## Retheming',
      '',
      'Every colour and size is a CSS custom property on the root element, so you can',
      'restyle the widget from the outside without touching anything inside it:',
      '',
      '```css',
      `.${rootClass(spec)} {`,
      tokenCssBlock(spec, props),
      '}',
      '```',
      '',
      '## Licence',
      '',
      'MIT. Ship it, sell it, change it, no attribution required.',
    ),
  }
}
